    location = /captcha.html {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /verify {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /_auth {
        internal;
        proxy_pass http://127.0.0.1:8000;
        proxy_pass_request_body off;          # 不把请求体透传，避免大文件上传被二次缓冲
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie; # 关键：透传用户 Cookie 供校验
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

######保护的接口
    location / {
        access_by_lua_block {
            local res = ngx.location.capture("/_auth")
            if res.status ~= 200 then
                return ngx.redirect("/captcha.html?back=" .. ngx.escape_uri(ngx.var.request_uri))
            end
        }
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 0;    # 上传大文件不限大小
        proxy_read_timeout 300s;   # 大文件上传/下载超时放宽

    }
